INCLUDE_DIRECTORIES(
  ${PROJECT_BINARY_DIR}/include
  ${PROJECT_SOURCE_DIR}/include
)

SET(testf_SOURCES
        test1/subr1.f
        test1/test1.f
)

FOREACH(testf_SOURCE ${testf_SOURCES})
  GET_FILENAME_COMPONENT(testf_BASE ${testf_SOURCE} NAME_WE)
  # Shared lib tests
  IF(MEDFILE_BUILD_SHARED_LIBS)
    SET(testf_SHARED_BIN "${testf_BASE}f")
    ADD_EXECUTABLE(${testf_SHARED_BIN} ${testf_SOURCE})
    TARGET_LINK_LIBRARIES(${testf_SHARED_BIN} med)
    SET_TARGET_PROPERTIES(${testf_SHARED_BIN} PROPERTIES OUTPUT_NAME ${testf_BASE})
    GET_TARGET_PROPERTY(TMP ${testf_SHARED_BIN} OUTPUT_NAME)
    INSTALL(TARGETS ${testf_SHARED_BIN} DESTINATION bin/testf)
    ADD_TEST("Test${testf_SHARED_BIN}" ${TMP})
  ENDIF()
ENDFOREACH(testf_SOURCE)
