name: med-deps
channels:
  - https://repo.prefix.dev/code-aster
  - conda-forge
dependencies:
  - python 3.11
  - hdf5 1.14.4.3
  - vswhere
  - cmake
  - make
  - zlib
  - ninja
  - swig >=4.0.2
  - libxml2
