{% set name = "libmed" %}
{% set version = "4.1.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 8

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}           # [not win]
    - swig >=4.0.2
    - sysroot_linux-64 2.17               # [unix]
    - cmake
    - ninja                               # [win]
    - make                                # [unix]
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - hdf5
    - zlib
  #    - {{ mpi }}                 # [mpi != "nompi"]
  run:
    - python
  #    - {{ mpi }}                 # [mpi != "nompi"]

test:
  imports:
    - med
  commands:
    - test -f ${PREFIX}/lib/libmed${SHLIB_EXT}                   # [unix]
    - nm ${PREFIX}/lib/libmedC.so | grep MEDlibraryNumVersion    # [linux]

about:
  home: https://www.salome-platform.org/user-section/about/med
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: 'MED : interoperable format for data interchange between mesh based solvers.'
  description: |
    The purpose of the MED module is to provide a standard for storing and recovering computer data associated to numerical meshes and fields, and to facilitate the exchange between codes and solvers.
  doc_url: http://www.salome-platform.org/
  dev_url: https://git.salome-platform.org/gitweb/?p=modules/med.git;a=summary

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
    - looooo
    - ldallolio-irt
